---
# RHEL-07-020110
- name: The Red Hat Enterprise Linux operating system must disable the file system automounter unless required
  ansible.builtin.systemd_service:
    name: autofs
    state: stopped
    enabled: false
  when: manage_204451 | bool
...