---
# RHEL-07-020260
- name: The Red Hat Enterprise Linux operating system security patches and updates must be installed and up to date
  ansible.builtin.package:
    name: '*'
    state: latest
  when: manage_204459 | bool

# RHEL-07-020000
- name: The Red Hat Enterprise Linux operating system must not have the rsh-server package installed
  ansible.builtin.package:
    name: rsh-server
    state: absent
  when: manage_204442 | bool

# RHEL-07-020010
- name: The Red Hat Enterprise Linux operating system must not have the ypserv package installed
  ansible.builtin.package:
    name: ypserv
    state: absent
  when: manage_204443 | bool

# RHEL-07-021710
- name: The Red Hat Enterprise Linux operating system must not have the telnet-server package installed
  ansible.builtin.package:
    name: telnet-server
    state: absent
  when: manage_204502 | bool

- name: Update package facts
  ansible.builtin.package_facts:
    manager: auto
  changed_when: false
...