---
# RHEL-07-020050
- name: The Red Hat Enterprise Linux operating system must prevent the installation of software, patches, service packs, device drivers, or operating system components from a repository without verification they have been digitally signed using a certificate that is issued by a Certificate Authority (CA) that is recognized and approved by the organization
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    regexp: '(?i)^[#\s]*gpgcheck'
    line: 'gpgcheck=1'
    state: present
  when: manage_204447 | bool

# RHEL-07-020060
- name: The Red Hat Enterprise Linux operating system must prevent the installation of software, patches, service packs, device drivers, or operating system components of local packages without verification they have been digitally signed using a certificate that is issued by a Certificate Authority (CA) that is recognized and approved by the organization
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    regexp: '(?i)^[#\s]*localpkg_gpgcheck'
    line: 'localpkg_gpgcheck=1'
    state: present
  when: manage_204448 | bool
...